# ~/.config/helix/config.toml

# theme = "onedark"
theme = "tokyonight"

[editor]
mouse = false
line-number = "relative"
cursorline = true
continue-comments = false
# auto-completion = false
bufferline = "always"
color-modes = true
popup-border = "all"
# end-of-line-diagnostics = "hint"

[editor.statusline]
# left = ["mode", "spinner", "file-name"]

[editor.lsp]
# snippets = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
# '{' = '}'

[editor.auto-save]
# focus-lost = true
# after-delay.enable = true


[editor.indent-guides]
render = true
# skip-levels = 0

[editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

# -------------------------------------------------------------------------

[keys.normal]

ret = ":update"
";" = "command_mode"

tab = ":buffer-next"
A-left = ":buffer-next"
A-right = ":buffer-previous"

# keys.insert overlap
C-left = "move_prev_word_start"
C-right = [ "move_next_word_end", "extend_char_right" ]

# keys.select overlap
space.s = "goto_word"
backspace = "collapse_selection"
g.o = "flip_selections"

# keys.insert and keys.select overlap

C-up = [ "page_cursor_half_up", "align_view_center" ]
C-down = [ "page_cursor_half_down", "align_view_center" ]


# sus
S-left = "extend_char_left"
S-down = "extend_visual_line_down"
S-up = "extend_visual_line_up"
S-right = "extend_char_right"

M = "save_selection"
g.M = "jump_backward"

# leader key
# not doing [keys.normal.space] because space.s
space.r = [ ":update", ":run-shell-command ~/.config/bin/run.sh %{buffer_name}" ]
space.w = ":buffer-close"
space.q = ":quit"

[keys.insert]
down.left = "normal_mode"
C-backspace = "delete_word_backward"

# overlap
C-left = "move_prev_word_start"
C-right = [ "move_next_word_end", "extend_char_right" ]

[keys.select]
C-left = "extend_prev_word_start"
C-right = [ "extend_next_word_end", "extend_char_right" ]

# overlap
space.s = "goto_word"
backspace = "collapse_selection"
g.o = "flip_selections"

C-up = [ "page_cursor_half_up", "align_view_center" ]
C-down = [ "page_cursor_half_down", "align_view_center" ]


