# ~/.config/helix/config.toml

# theme = "onedark"
theme = "tokyonight"

[editor]
# scrolloff = 999
# mouse = false
scroll-lines = 1
line-number = "relative"
cursorline = true
continue-comments = false
# auto-completion = false
bufferline = "always"
color-modes = true
popup-border = "all"
# end-of-line-diagnostics = "hint"

[editor.statusline]
# left = ["mode", "spinner", "file-name"]

[editor.lsp]
# snippets = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# [editor.auto-pairs]
# '{' = '}'

[editor.auto-save]
# focus-lost = true
after-delay.enable = true
# after-delay.timeout = 5000

[editor.whitespace]
# render = "all"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.indent-guides]
render = true
# skip-levels = 0

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

# -------------------------------------------------------------------------

[keys.normal]

# basic
ret = ":update"
"?" = "command_mode"

tab = ":buffer-next"
S-tab = ":buffer-previous"
A-left = ":buffer-previous"
A-right = ":buffer-next"

# sus
S-left = "extend_char_left"
S-down = "extend_visual_line_down"
S-up = "extend_visual_line_up"
S-right = "extend_char_right"

# too sus
# M = "save_selection"
# g.M = "jump_backward"

# leader key
# not doing [keys.normal.space] because space.s
space.r = [ ":update", ":run-shell-command run.sh %{buffer_name}" ]
space.w = ":buffer-close"
space.q = ":quit"

# keys.normal
C-left = "move_prev_word_start"
C-right = "move_next_word_end"

# keys.select overlap
space.s = "goto_word"
backspace = "collapse_selection"
g.o = "flip_selections"

# keys.insert and keys.select overlap

pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"

home = "goto_first_nonwhitespace"


[keys.insert]
# down.left = "normal_mode"
C-backspace = "delete_word_backward"

C-left = "move_prev_word_start"
C-right =  [ "move_next_word_end", "move_char_right" ]

# overlap
pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"

home = "goto_first_nonwhitespace"

[keys.select]
C-left = "extend_prev_word_start"
C-right = [ "extend_next_word_end", "extend_char_right" ]

# overlap
space.s = "goto_word"
backspace = "collapse_selection"
g.o = "flip_selections"

pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"

home = "goto_first_nonwhitespace"

