# nilognap's helix config.toml

# theme = "onedark"
theme = "tokyonight"


[editor]
mouse = false
line-number = "relative"
cursorline = true
continue-comments = false
# auto-completion = false
bufferline = "always"
color-modes = true
popup-border = "all"
# end-of-line-diagnostics = "hint"

[editor.statusline]
# left = ["mode", "spinner", "file-name"]

[editor.lsp]
# snippets = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'{' = '}'

[editor.auto-save]
# focus-lost = true
# after-delay.enable = true


[editor.indent-guides]
render = true
# skip-levels = 0

[editor.inline-diagnostics]
# cursor-line = "hint"
# other-lines = "error"

# ---------------------------------------------------------------------------------

[keys.normal]
"ret" = ":update"

# leader key
"space"."ret" = ":update"
"space".q = [":update", ":quit"]
Z.Z = [":update", ":quit"]

# "space".r = [":update", ":run-shell-command ~/.config/helix/run.sh %{buffer_name}"]
"space".r = [":update", ":run-shell-command %sh{~/.config/helix/run.sh %{buffer_name}}"]

"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

H = ["page_cursor_half_up", "align_view_center"]
L = ["page_cursor_half_down", "align_view_center"]

# sus
M = "save_selection"
g.M = "jump_backward"

# vim muslce memory
# 0 = "goto_first_nonwhitespace"


[keys.select]

H = ["page_cursor_half_up", "align_view_center"]
L = ["page_cursor_half_down", "align_view_center"]

# vim muscle memory
# 0 = "goto_first_nonwhitespace"

[keys.insert]
j.k = "normal_mode"
